export const CONSTANTS = {
  DEFAULT_HOURLY_RATE: 300,
  MINUTES_PER_HOUR: 60,
  LOADING_SCREEN_DELAY_MS: 2000,
  LOADING_SCREEN_FADE_MS: 500,
  VALIDATION_ERROR_ANIMATION_MS: 300,
  BUTTON_ANIMATION_MS: 150,
  TOAST_AUTO_DISMISS_MS: 5000,
};
